# Generated by Django 6.0.7 on 2026-07-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aldeia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Aldeia')),
                ('municipio', models.CharField(max_length=100)),
                ('populacao', models.PositiveIntegerField(default=0)),
                ('quantidade_reservatorios', models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade de reservatórios')),
                ('capacidade_total', models.PositiveIntegerField(default=0, help_text='Capacidade total instalada em litros')),
                ('possui_energia', models.BooleanField(default=False)),
                ('possui_espaco_ubsi', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True)),
            ],
        ),
    ]
