# Generated by Django 6.0.7 on 2026-07-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aldeias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aldeia',
            name='estado',
            field=models.CharField(default='RS', max_length=2),
        ),
        migrations.AddField(
            model_name='aldeia',
            name='etnia',
            field=models.CharField(choices=[('GM', 'Guarani Mbyá'), ('KA', 'Kaingang'), ('CH', 'Charrua'), ('XO', 'Xokleng')], default=0, max_length=2, verbose_name='Etnia'),
            preserve_default=False,
        ),
    ]
